# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
my_array = np.array([9, 70, 3, 7, 41])
print(my_array)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
my_array.sort()
print(my_array)

[ 9 70  3  7 41]
[ 3  7  9 41 70]


# Problem 2

In [4]:
import random
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array([10,15,30,45,60])
print(a)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b = np.arange(5, 16)
print(b)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange(50,101,5)
print(c)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d = np.zeros(10)
print(d)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e = np.ones(10)
print(e)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f = np.linspace(0,100,5)
print(f)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g = np.random.randint(10,30,5)
print(g)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
h = np.random.normal(-1,1,10)
print(h)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris = np.random.randint(10,50,[3,5])
print(matris)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(matris.sum(axis=0))
print(matris.sum(axis=1))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(matris.max(axis=None))
print(matris.min(axis=None))
print(matris.mean(axis=None))

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(np.where(matris== matris.max(axis=None)))


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
arr=np.arange(10,21)
print(arr[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(arr[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(matris[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matris[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matris[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(matris**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris2=np.arange(-50,50)
matris2.reshape(10,10)
print(matris2)
print("Negatif", matris2[matris2<0])
print("Pozitif", matris2[matris2>0])


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[15 20 21 13 16]
[-0.8619385  -1.79102286  0.24374589 -0.06529729 -1.66951511 -0.37954177
 -2.30763426 -1.95078673 -3.32323886 -0.50984762]
[[49 27 21 42 37]
 [40 47 27 23 33]
 [48 20 20 37 26]]
[137  94  68 102  96]
[176 170 151]
49
20
33.13333333333333
(array([0], dtype=int64), array([0], dtype=int64))
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[49 27 21 42 37]
27
[49 40 48]
[[2401  729  441 1764 1369]
 [1600 2209  729  529 1089]
 [2304  400  400 1369  676]]
[-50 -49 -48 -47 -46 -45 -44 -43 -42 -41 -40 -39 -38 -37 -36 -35 -34 -33
 -32 -31 -30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15
 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3
   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  31  32  33  3