# Problem 1

In [4]:
# 1 - numpy kütüphanesini import edin
import numpy as np
import numpy

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.random.randint(10,size=5)
print(a)

# 3 - matris'in boyutunu öğrenin
print(a.size)

# 4 - matris'i yeniden boyutlandırın
a.reshape(5,1)

# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)


[5 7 6 4 7]
5
1


# Problem 2

In [8]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a= np.arange(1,10,2)
print(a)

# 2 - Oluşturduğunuz matrisi parçalayın
x,y,z= np.split(a,[2,4])

print(x, y, z)

# 3 - Parçalanmış matrisleri birleştirin
np.concatenate([x,y,z])

[1 3 5 7 9]
[1 3] [5 7] [9]


array([1, 3, 5, 7, 9])

# Problem 3

In [21]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
a = np.random.randint(6, 101, 10)
a=a[:10]
print(a)

# 2 - matris'in özelliklerini inceleyin
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[52 55 62  8 11 65 71 50 86 60]
(10,)
1
10
int32
