# Numpy

In [4]:
import numpy as np #as np demek ben bunu np olarak kısalttım , np ile çağıracağım demek

a = np.array([1,2,3,4])

b = np.array([2,3,4,5])

print(a*b)

[ 2  6 12 20]


In [5]:
x = np.array([1,2,3,4,5,6,7,8,9])  

multi = x.reshape(3,3)  # reshape ile satır ve stunları ayarlayıp gruplandırıyorum.
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(multi.shape) # arreylerin boyutunu verir.

(3, 3)


# Birleştirme = .concatenate()

In [7]:
x = np.array([1,2,3,4,5,])  #liste gibi tanımlıyoruz.

y = np.array([6,7,8,9,10])

print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
a = np.array([[1,2,3], [4,5,6]])

print(np.concatenate([a,a]))
 

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


axis= 0 ise satırda birleştirir.

axis=1 ise sütunda birleştirir.

In [14]:
print(np.concatenate([a,a], axis=1 ))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [15]:
m = np.array([1,2,3,99,80,4,5,9])

print(np.split(m, [3,5]))  #split ile ayırma yaparız. 3. ve 5. elemandan itibaren ayır.


[array([1, 2, 3]), array([99, 80]), array([4, 5, 9])]


In [16]:
a, b, c = np.split(m, [3,5]) 
#m listesini 3. ve 5. karakterden itibaren ayır. 3 grup olacak bunları a,b ve c olarak yaz.
print(a)
print(b)
print(c)

[1 2 3]
[99 80]
[4 5 9]


In [17]:
n = np.arange(16).reshape(4,4) # arange = 1 den 15 e kadar sayı yaz.

np.vsplit(n, [2]) #vsplit=yatay olarak ayır. vsplit(n, [2])=ortadan ikiye ayır

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [18]:
np.hsplit(n, [2]) #dikey ayırma yaptı

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [19]:
np.arange(3, 12, 2) #3 ten başla, 11 de bitir, 2 şer 2 şer git

array([ 3,  5,  7,  9, 11])

In [20]:
np.zeros(5) #sıfırlardan oluşan bir numpy dizisi verir


array([0., 0., 0., 0., 0.])

In [21]:
np.ones(6) #1 lerden oluşan numpy dizisi ver

array([1., 1., 1., 1., 1., 1.])

In [26]:
np.linspace(3, 12, 4) #3 ten başla 12 de bitir, 4 aralığa böl

array([ 3.,  6.,  9., 12.])

In [28]:
np.random.randint(0,10,3) #0 ile 10 arasında rastgele 3 sayı üret

array([3, 2, 2])

In [30]:
npArray = np.arange(50)
npMulti = npArray.reshape(5, 10)
print(npMulti.sum(axis = 1))

[ 45 145 245 345 445]


# Numpy Array'in Özellikleri

- ndim = boyut sayısı
- shap = boyut bilgisi
- size = toplam eleman sayı
- dtype = veri tipi
 

In [33]:
a = np.random.randint(10, size=10)

print(a.ndim) # boyutu 
print(a.shape) # boyut bilgisi eleman sayısı
print(a.size)  
print(a.dtype)

1
(10,)
10
int32


In [36]:
v = np.array([20,8,90,77,265,10,38])

v.sort()
print(v)

[  8  10  20  38  77  90 265]


# Index ile Elemanlara Erişmek

In [37]:
a = np.random.randint(10, size=10)
print(a[0])

7


In [38]:
a[0] = 100

In [39]:
print(a[0])

100


In [40]:
x = np.random.randint(10, size=(3,5))
print(x)

[[6 3 1 6 2]
 [7 9 7 6 3]
 [7 6 6 1 3]]


In [41]:
print(x[0,0])

6


In [42]:
x[1, 4] = 100
print(x)

[[  6   3   1   6   2]
 [  7   9   7   6 100]
 [  7   6   6   1   3]]


# Slicing ile Elemanlara Erişme

In [43]:
a = np.arange(20, 30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [45]:
print(a[0:3]) # 0 dan 3. elemana kadar yazdır

[20 21 22]


In [47]:
print(a[3:]) # 3 ten en son elemana kadar yazdır

[23 24 25 26 27 28 29]


In [48]:
print(a[1::2]) #1 den başla 2 şer 2 şer atla

[21 23 25 27 29]


In [49]:
print(a[2::2]) #2. elemandan başla ve 2 şer 2 şer yazdır.

[22 24 26 28]


In [51]:
k = np.random.randint(10, size=[5,5])

print(k)

[[9 2 8 8 5]
 [7 7 7 0 3]
 [8 1 7 0 0]
 [8 7 3 5 2]
 [7 6 4 6 4]]


In [53]:
print(k[:,0]) #stunlardaki ilk elemanları al

[9 7 8 8 7]


In [57]:
print(k[0,:]) #ilk satır

[9 2 8 8 5]


# Alt küme Üzerinde İşlem Yapmak

In [58]:
print(z)

[[1 5 5 0 9]
 [7 6 2 4 5]
 [4 3 3 8 8]
 [4 7 5 6 8]
 [6 0 2 9 5]]


In [60]:
alt_z = z[0:3, 0:2]

print(alt_z)

[[1 5]
 [7 6]
 [4 3]]


# TOPLU GETİRME İŞLEMİ

In [63]:
v = np.arange(0, 30, 3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [65]:
yetgen = [1, 3, 5]
print(v[yetgen]) #1. 3. ve 5. elemanları toplu getir.

[ 3  9 15]


# Koşullu Eleman İşlemleri

In [67]:
g = np.array([1, 2, 3, 4, 5])
print(g > 3)

[False False False  True  True]


In [70]:
print(g[ g > 3]) #3 ten büyükleri getir

[4 5]


# Matematiksel İşlemler

In [73]:
g = np.array([1, 2, 3, 4, 5])

print( g * 2)

[ 2  4  6  8 10]


In [75]:
print( g**2)

[ 1  4  9 16 25]


In [77]:
print(np.subtract(g,3)) # her birinden 3 çıkarır

[-2 -1  0  1  2]


In [78]:
print(np.add(g,2)) # her birine iki ekler

[3 4 5 6 7]


In [80]:
np.multiply(g, 2) # çarpma işlemi yapar

array([ 2,  4,  6,  8, 10])

In [81]:
np.divide(g, 2) #bölme

array([0.5, 1. , 1.5, 2. , 2.5])

In [83]:
np.power(g, 2) # üs alma

array([ 1,  4,  9, 16, 25], dtype=int32)

In [84]:
np.mod(g, 5) # mod alma

array([1, 2, 3, 4, 0], dtype=int32)

In [85]:
print(np.absolute(g)) # mutlak değer alma

[1 2 3 4 5]


# iki bilinmeyenli denklem çözme

In [92]:
# 5*x0 + x1 = 12

a = np.array([[5,1]])
b = np.array([12])
x = np.linalg.solve(a, b)

print(x)

LinAlgError: Last 2 dimensions of the array must be square